// src/features/gestionar-insumos/logic/api/mock.ts
import type{ Insumo } from './types';

export const MOCK_INSUMOS: Insumo[] = [
  {
    id: '1',
    codigo: 'INS-0001',
    nombre: 'Filete de Lenguado',
    categoria: 'Pescados',
    unidadMedida: 'kg',
    stockActual: 8,
    stockMinimo: 5,
    stockAbasto: 15,
    estado: 'Activo',
    nivelStock: 'OK',
  },
  {
    id: '2',
    codigo: 'INS-0002',
    nombre: 'Camarón Gigante',
    categoria: 'Mariscos',
    unidadMedida: 'kg',
    stockActual: 3,
    stockMinimo: 5,
    stockAbasto: 12,
    estado: 'Activo',
    nivelStock: 'Bajo',
  },
  {
    id: '3',
    codigo: 'INS-0003',
    nombre: 'Pulpo Rojo',
    categoria: 'Mariscos',
    unidadMedida: 'kg',
    stockActual: 12,
    stockMinimo: 4,
    stockAbasto: 10,
    estado: 'Activo',
    nivelStock: 'OK',
  },
  {
    id: '4',
    codigo: 'INS-0004',
    nombre: 'Ají Amarillo',
    categoria: 'Verduras',
    unidadMedida: 'kg',
    stockActual: 2,
    stockMinimo: 3,
    stockAbasto: 8,
    estado: 'Activo',
    nivelStock: 'Bajo',
  },
  {
    id: '5',
    codigo: 'INS-0005',
    nombre: 'Limón Sutil',
    categoria: 'Verduras',
    unidadMedida: 'kg',
    stockActual: 15,
    stockMinimo: 5,
    stockAbasto: 20,
    estado: 'Activo',
    nivelStock: 'OK',
  },
  {
    id: '6',
    codigo: 'INS-0006',
    nombre: 'Cerveza Cristal',
    categoria: 'Bebidas',
    unidadMedida: 'caja',
    stockActual: 6,
    stockMinimo: 2,
    stockAbasto: 10,
    estado: 'Activo',
    nivelStock: 'OK',
  },
  {
    id: '7',
    codigo: 'INS-0007',
    nombre: 'Culantro Fresco',
    categoria: 'Verduras',
    unidadMedida: 'kg',
    stockActual: 0,
    stockMinimo: 2,
    stockAbasto: 5,
    estado: 'Activo',
    nivelStock: 'Critico',
  },
  {
    id: '8',
    codigo: 'INS-0008',
    nombre: 'Envase Cevichero 32 oz',
    categoria: 'Envases',
    unidadMedida: 'caja',
    stockActual: 4,
    stockMinimo: 3,
    stockAbasto: 8,
    estado: 'Activo',
    nivelStock: 'OK',
  },
  {
    id: '9',
    codigo: 'INS-0009',
    nombre: 'Sal de Mesa',
    categoria: 'Condimentos',
    unidadMedida: 'kg',
    stockActual: 10,
    stockMinimo: 3,
    stockAbasto: 15,
    estado: 'Activo',
    nivelStock: 'OK',
  },
  {
    id: '10',
    codigo: 'INS-0010',
    nombre: 'Alga Marina Wakame',
    categoria: 'Abarrotes',
    unidadMedida: 'g',
    stockActual: 500,
    stockMinimo: 200,
    stockAbasto: 1000,
    estado: 'Inactivo',
    nivelStock: 'OK',
  },
];