import type { Insumo } from '../interfaces/insumo.types';

export const MOCK_INSUMOS: Insumo[] = [
  {
    id: '1',
    codigo: 'INS-0001',
    nombre: 'Filete de Lenguado',
    descripcion: 'Filete fresco de lenguado para preparación de platos marinos.',
    categorias: ['Pescados', 'Mariscos'],
    unidadMedida: 'kg',
    stockActual: 8,
    stockMinimo: 5,
    stockAbasto: 15,
    estado: 'Activo',
    nivelStock: 'OK',
  },
  {
    id: '2',
    codigo: 'INS-0002',
    nombre: 'Camarón Gigante',
    descripcion: 'Camarón fresco de tamaño grande para platos y entradas.',
    categorias: ['Mariscos', 'Pescados'],
    unidadMedida: 'kg',
    stockActual: 3,
    stockMinimo: 5,
    stockAbasto: 12,
    estado: 'Activo',
    nivelStock: 'Bajo',
  },
  {
    id: '3',
    codigo: 'INS-0003',
    nombre: 'Pulpo Rojo',
    descripcion: 'Pulpo fresco seleccionado para preparaciones marinas.',
    categorias: ['Mariscos'],
    unidadMedida: 'kg',
    stockActual: 12,
    stockMinimo: 4,
    stockAbasto: 10,
    estado: 'Activo',
    nivelStock: 'OK',
  },
  {
    id: '4',
    codigo: 'INS-0004',
    nombre: 'Ají Amarillo',
    descripcion: 'Ají amarillo fresco utilizado en diversas preparaciones.',
    categorias: ['Verduras', 'Condimentos'],
    unidadMedida: 'kg',
    stockActual: 2,
    stockMinimo: 3,
    stockAbasto: 8,
    estado: 'Activo',
    nivelStock: 'Bajo',
  },
  {
    id: '5',
    codigo: 'INS-0005',
    nombre: 'Limón Sutil',
    descripcion: 'Limón fresco para ceviches, bebidas y aderezos.',
    categorias: ['Verduras', 'Condimentos'],
    unidadMedida: 'kg',
    stockActual: 15,
    stockMinimo: 5,
    stockAbasto: 20,
    estado: 'Activo',
    nivelStock: 'OK',
  },
  {
    id: '6',
    codigo: 'INS-0006',
    nombre: 'Cerveza Cristal',
    descripcion: 'Bebida envasada destinada al servicio del restaurante.',
    categorias: ['Bebidas'],
    unidadMedida: 'caja',
    stockActual: 6,
    stockMinimo: 2,
    stockAbasto: 10,
    estado: 'Activo',
    nivelStock: 'OK',
  },
  {
    id: '7',
    codigo: 'INS-0007',
    nombre: 'Culantro Fresco',
    descripcion: 'Hierba fresca utilizada como ingrediente y decoración.',
    categorias: ['Verduras', 'Condimentos', 'Abarrotes'],
    unidadMedida: 'kg',
    stockActual: 0,
    stockMinimo: 2,
    stockAbasto: 5,
    estado: 'Activo',
    nivelStock: 'Critico',
  },
  {
    id: '8',
    codigo: 'INS-0008',
    nombre: 'Envase Cevichero 32 oz',
    descripcion: 'Envase descartable de 32 oz para despacho de ceviches.',
    categorias: ['Envases'],
    unidadMedida: 'caja',
    stockActual: 4,
    stockMinimo: 3,
    stockAbasto: 8,
    estado: 'Activo',
    nivelStock: 'OK',
  },
  {
    id: '9',
    codigo: 'INS-0009',
    nombre: 'Sal de Mesa',
    descripcion: 'Sal refinada para preparación y condimentación de alimentos.',
    categorias: ['Condimentos', 'Abarrotes'],
    unidadMedida: 'kg',
    stockActual: 10,
    stockMinimo: 3,
    stockAbasto: 15,
    estado: 'Activo',
    nivelStock: 'OK',
  },
  {
    id: '10',
    codigo: 'INS-0010',
    nombre: 'Alga Marina Wakame',
    descripcion: 'Alga deshidratada utilizada en preparaciones de cocina marina.',
    categorias: ['Abarrotes', 'Mariscos'],
    unidadMedida: 'g',
    stockActual: 500,
    stockMinimo: 200,
    stockAbasto: 1000,
    estado: 'Inactivo',
    nivelStock: 'OK',
  },
];