/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MesasRouteImport } from './routes/mesas'
import { Route as AbastecimientoRouteImport } from './routes/abastecimiento'
import { Route as AbastoRouteImport } from './routes/abasto'
import { Route as InsumosRouteImport } from './routes/insumos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MesasRouteImport } from './routes/mesas'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as KardexRouteImport } from './routes/kardex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesasRoute = MesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => rootRouteImport,
} as any)
const AbastecimientoRoute = AbastecimientoRouteImport.update({
  id: '/abastecimiento',
  path: '/abastecimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const AbastoRoute = AbastoRouteImport.update({
  id: '/abasto',
  path: '/abasto',
  getParentRoute: () => rootRouteImport,
} as any)
const InsumosRoute = InsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MesasRoute = MesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const KardexRoute = KardexRouteImport.update({
  id: '/kardex',
  path: '/kardex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mesas': typeof MesasRoute
  '/abastecimiento': typeof AbastecimientoRoute
  '/abasto': typeof AbastoRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/mesas': typeof MesasRoute
  '/proveedores': typeof ProveedoresRoute
  '/usuarios': typeof UsuariosRoute
  '/kardex': typeof KardexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abastecimiento': typeof AbastecimientoRoute
  '/abasto': typeof AbastoRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/mesas': typeof MesasRoute
  '/proveedores': typeof ProveedoresRoute
  '/usuarios': typeof UsuariosRoute
  '/mesas': typeof MesasRoute
  '/kardex': typeof KardexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mesas': typeof MesasRoute
  '/abastecimiento': typeof AbastecimientoRoute
  '/abasto': typeof AbastoRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/mesas': typeof MesasRoute
  '/proveedores': typeof ProveedoresRoute
  '/usuarios': typeof UsuariosRoute
  '/kardex': typeof KardexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/' | '/kardex' 
    | '/mesas'
    | '/abastecimiento'
    | '/abasto'
    | '/insumos'
    | '/login'
    | '/mesas'
    | '/proveedores'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/' | '/kardex' 
    | '/mesas'
    | '/abastecimiento'
    | '/abasto'
    | '/insumos'
    | '/login'
    | '/mesas'
    | '/proveedores'
    | '/usuarios'
  id:
    | '__root__'
    | '/' | '/kardex' 
    | '/mesas'
    | '/abastecimiento'
    | '/abasto'
    | '/insumos'
    | '/login'
    | '/mesas'
    | '/proveedores'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbastecimientoRoute: typeof AbastecimientoRoute
  AbastoRoute: typeof AbastoRoute
  InsumosRoute: typeof InsumosRoute
  LoginRoute: typeof LoginRoute
  MesasRoute: typeof MesasRoute
  ProveedoresRoute: typeof ProveedoresRoute
  UsuariosRoute: typeof UsuariosRoute
  MesasRoute: typeof MesasRoute
  KardexRoute: typeof KardexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abastecimiento': {
      id: '/abastecimiento'
      path: '/abastecimiento'
      fullPath: '/abastecimiento'
      preLoaderRoute: typeof AbastecimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abasto': {
      id: '/abasto'
      path: '/abasto'
      fullPath: '/abasto'
      preLoaderRoute: typeof AbastoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insumos': {
      id: '/insumos'
      path: '/insumos'
      fullPath: '/insumos'
      preLoaderRoute: typeof InsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesas': {
      id: '/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof MesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesas': {
      id: '/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof MesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kardex': {
      id: '/kardex'
      path: '/kardex'
      fullPath: '/kardex'
      preLoaderRoute: typeof KardexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbastecimientoRoute: AbastecimientoRoute,
  AbastoRoute: AbastoRoute,
  InsumosRoute: InsumosRoute,
  LoginRoute: LoginRoute,
  MesasRoute: MesasRoute,
  ProveedoresRoute: ProveedoresRoute,
  UsuariosRoute: UsuariosRoute,
  MesasRoute: MesasRoute,
  KardexRoute: KardexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
